// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahtqiuhimddklgkrevzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFodHFpdWhpbWRka2xna3JldnppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1Njc5ODMsImV4cCI6MjA3MTE0Mzk4M30.asYR6zp7-6nbBopx3dspFjQnHOYrQ9Jd7mpeS_t5RY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});